version: '2'
services:
  web:
    build: .
    volumes:
      - ./app:/app
    ports:
      - "7000:5000"
    expose:
      - "7000"
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
      - 'RUN=flask run --host=0.0.0.0 --port=5000'
    command: flask run --host=0.0.0.0 --port=5000